spring:
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: 172.19.16.233:8848
        namespace: promotion
        group: promotion
      password: nacos
      username: nacos
  application:
    name: test-gateway
gray:
  loadbalancer:
    enabled: true
    weight: 80

server:
  port: 8083
